env:
  browser: true
  es2021: true
extends:
  - standard
  - "eslint:recommended"
  - "prettier"
parserOptions:
  ecmaVersion: 12
  sourceType: module
ignorePatterns:
  - "*.test.js"
  - "*.js"
  - "*.js.map"
rules: {}
