################
# BUILDER NODE #
################

FROM node:20.8.1-alpine AS node-builder
WORKDIR /usr/src/app

# copy assets
COPY package.json package-lock.json webpack.config.js gulpfile.js ./
COPY assets assets

# build js and css deps
RUN npm install && npm run build

#########
# FINAL #
#########

FROM python:3.12

# Create non-root user to run Gens
RUN groupadd --gid 1000 worker \
    && useradd -g worker --uid 1000 --shell /user/sbin/nologin --create-home worker

# Copy project to worker dir
WORKDIR /home/worker

# Chown all the files to the app user
COPY --chown=worker:worker gens ./gens
COPY --chown=worker:worker utils ./utils
COPY --chown=worker:worker README.md LICENSE pyproject.toml ./

# copy compiled web assetes
COPY --chown=worker:worker --from=node-builder /usr/src/app/build/css/error.min.css gens/static/css/
COPY --chown=worker:worker --from=node-builder /usr/src/app/build/css/home.min.css /usr/src/app/build/css/landing.min.css /usr/src/app/build/css/about.min.css gens/blueprints/home/static/
COPY --chown=worker:worker --from=node-builder /usr/src/app/build/*/gens.min.* gens/blueprints/gens/static/

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install -e .

# Change the user to app
USER worker

ENV FLASK_APP=./gens

CMD flask run --reload --debug --host '0.0.0.0'