version: "3.8"
services:
  mongodb:
    container_name: mongodb_jakob
    image: mongo:latest
  gens:
    container_name: gens_jakob
    build:
      context: .
      network: host
    expose:
      - '5000'
    ports:
      - "8820:5000"
    networks:
      - gens-net
    depends_on:
      - mongodb
    command: "flask run --host 0.0.0.0"

networks:
  gens-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.37.0.0/24
