"""Collection names for the database."""

SAMPLES_COLLECTION = "samples"
ANNOTATIONS_COLLECTION = "annotations"
ANNOTATION_TRACKS_COLLECTION = "annotation-tracks"
TRANSCRIPTS_COLLECTION = "transcripts"
UPDATES_COLLECTION = "updates"
CHROMSIZES_COLLECTION = "chrom-sizes"
USER_COLLECTION = "user"
SAMPLE_ANNOTATIONS_COLLECTION = "sample-annotations"
SAMPLE_ANNOTATION_TRACKS_COLLECTION = "sample-annotation-tracks"
